version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb:10.9
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin  
    ports:
      - 8080:80   
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=1024M
      - MAX_EXECUTION_TIME=300
    volumes:
      - ./db/data:/var/lib/mysql
